In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

## ***Numpy***

In [5]:
import sys
import numpy as np
print(np.__version__)

2.0.2

In [11]:
py_array=[1,4,5,"Hello","Abid"]
np_array=np.array([1,2,3,4,5,6],dtype=np.int8)

In [12]:
print(sys.getsizeof(py_array))  # size of the list container only, not the elements size

print(sys.getsizeof(np_array))  # returns the size of the NumPy array object, not just the raw data.
print(np_array.nbytes)  # Actual np.array size
print(np_array.itemsize)

104
118
6
1

In [13]:
import sys
import numpy as np

py_arr = [1, 2, 3, 4, 5]

np_array = np.array([1, 2, 3, 4, 5], dtype=np.int8)

print("Python list:", sys.getsizeof(py_arr))
print("NumPy array:", sys.getsizeof(np_array))
print("NumPy data:", np_array.nbytes)

Python list: 104
NumPy array: 117
NumPy data: 5

In [ ]:
# size of py_list
total_size = sys.getsizeof(py_array) # size of the list container only, not the elements size

for item in py_array:
    total_size += sys.getsizeof(item)

print(total_size)

244

In [14]:
import sys

py_arr = [1, 2, 3, 4, 5]

list_memory = sys.getsizeof(py_arr)
items_memory = sum(sys.getsizeof(item) for item in py_arr)

total_memory = list_memory + items_memory

print("List container:", list_memory)
print("Items:", items_memory)
print("Total:", total_memory)

List container: 104
Items: 140
Total: 244

In [15]:
import numpy as np
import sys

py_array = [1,2,3,4,5]
np_array = np.array([1,2,3,4,5], dtype=np.int32)

print(sys.getsizeof(py_array))      # list container size
print(np_array.nbytes)              # actual data size

104
20

In [ ]:
import sys
print(sys.getsizeof(py_array))
print(sys.getsizeof(np_array))

104
132

In [ ]:
py_list=[1,4,5,"Hello","Abid"]
np_array=np.array([1,2,3,4,5,6],dtype=np.int8)

In [ ]:
x=sys.getsizeof(1)*len(py_list)
print(x)

140

In [ ]:
print(np_array.nbytes)

6

In [ ]:
x=np_array.itemsize*np_array.size  # itemsize=memory used by one element, size=number of the element
print(x)

6

In [ ]:
print(np_array.itemsize)

1

In [ ]:
print(np_array.size)

6

In [ ]:
x=np_array.itemsize
print(x)
y=np_array.size
print(y)

1
6

In [ ]:
import time
import numpy as np
size=10000000
py_list=list(range(size))
np_arr=np.array(range(size))

In [ ]:
start_time=time.time()
py_result=[i*2 for i in py_list]
py_time=time.time()-start_time
print(py_time)

0.46423935890197754

In [ ]:
start_time=time.time()
np_result=np_arr*2
np_time=time.time()-start_time
print(np_time)

0.03415203094482422

In [ ]:
print(f"numpy array is {py_time/np_time:.2f} times faster than python list")

numpy array is 13.59 times faster than python list

In [ ]:
lst=[1,2,3,4]
np_arr=np.array(lst)
print(np_arr)
print(type(lst))

[1 2 3 4]
<class 'list'>

In [ ]:
np.arr=np.array([[2,2,3],[1,8,6]])
print(np.arr)

[[2 2 3]
 [1 8 6]]

In [ ]:
print(np.ones([3,2]))

[[1. 1.]
 [1. 1.]
 [1. 1.]]

In [ ]:
np.arr=np.ones((3,3,2,3))
print(np.arr)

[[[[1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]]]]

In [ ]:
print(np.shape(np.arr))

(3, 3, 2, 3)

In [ ]:
print(np.arr.reshape(9,2,3))

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]

In [ ]:
print(np.arange(0,16))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

In [ ]:
print(np.arr.ravel())

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1.]

In [ ]:
import pandas as pd
print(pd.__version__)

2.2.2

In [ ]:
data=[10,20,30,40,50,60]
df=pd.Series(data)
print(df)

0    10
1    20
2    30
3    40
4    50
5    60
dtype: int64

In [ ]:
print(df.value_counts())
print(df.index)
print(df.dtype)
print(df.values)

10    1
20    1
30    1
40    1
50    1
60    1
Name: count, dtype: int64
RangeIndex(start=0, stop=6, step=1)
int64
[10 20 30 40 50 60]

In [ ]:
print(df.tail(2))
print(df.head(2))
print(df.describe())
print(df.min())
print(df.max())
print(df.mean())
print(df.std())
print(df.var())
print(df.median())

4    50
5    60
dtype: int64
0    10
1    20
dtype: int64
count     6.000000
mean     35.000000
std      18.708287
min      10.000000
25%      22.500000
50%      35.000000
75%      47.500000
max      60.000000
dtype: float64
10
60
35.0
18.708286933869708
350.0
35.0

In [ ]:
# print(df)
labels=['a','b','c','d','e','f']
df=pd.Series(data,index=labels)
print(df)

a    10
b    20
c    30
d    40
e    50
f    60
dtype: int64

In [ ]:
print(df['a'])
print(df['b'])
print(df[3])

10
20
40

In [ ]:
print(df)

In [ ]:
print(df+10)
print(df*2)
print(df**2)

a    20
b    30
c    40
d    50
e    60
f    70
dtype: int64
a     20
b     40
c     60
d     80
e    100
f    120
dtype: int64
a     100
b     400
c     900
d    1600
e    2500
f    3600
dtype: int64

In [ ]:
import numpy as np
print(np.square(df))
print(np.sqrt(df))
print(np.pow(df,2))

a     100
b     400
c     900
d    1600
e    2500
f    3600
dtype: int64
a    3.162278
b    4.472136
c    5.477226
d    6.324555
e    7.071068
f    7.745967
dtype: float64
a     100
b     400
c     900
d    1600
e    2500
f    3600
dtype: int64

In [ ]:
print(df.sort_values())

a    10
b    20
c    30
d    40
e    50
f    60
dtype: int64

In [ ]:
print(df.apply(lambda x:x**2))

a     100
b     400
c     900
d    1600
e    2500
f    3600
dtype: int64

In [ ]:
print(np.square(df))
print(np.pow(df,3))
print(df*df)

a     100
b     400
c     900
d    1600
e    2500
f    3600
dtype: int64
a      1000
b      8000
c     27000
d     64000
e    125000
f    216000
dtype: int64
a     100
b     400
c     900
d    1600
e    2500
f    3600
dtype: int64

In [ ]:
for value in df:
  print(f"Value {value**2}")

Value 100
Value 400
Value 900
Value 1600
Value 2500
Value 3600

In [ ]:
filtered=df[df>40]
print(filtered)
print(df[(df>20) & (df<50)])

e    50
f    60
dtype: int64
c    30
d    40
dtype: int64

In [ ]:
print(df.describe())
print(df.info())

count     6.000000
mean     35.000000
std      18.708287
min      10.000000
25%      22.500000
50%      35.000000
75%      47.500000
max      60.000000
dtype: float64
<class 'pandas.core.series.Series'>
Index: 6 entries, a to f
Series name: None
Non-Null Count  Dtype
--------------  -----
6 non-null      int64
dtypes: int64(1)
memory usage: 268.0+ bytes
None

In [ ]:
data={'Name':['Abid','Rasel','Khan','Junaed','Siddik','Bahar'],
       'Age':[25,26,28,29,30,35],
       'Country':['Bangladesh','Pakistan','China',"Japan","Nepal",'Canada'],
       'Marks':[98,39,50,33,78,80]

}
dfe=pd.DataFrame(data,index=['a','b','c','d','e','f'])
print(dfe)

     Name  Age     Country  Marks
a    Abid   25  Bangladesh     98
b   Rasel   26    Pakistan     39
c    Khan   28       China     50
d  Junaed   29       Japan     33
e  Siddik   30       Nepal     78
f   Bahar   35      Canada     80

In [ ]:
print(dfe[['Age','Country']])

   Age     Country
a   25  Bangladesh
b   26    Pakistan
c   28       China
d   29       Japan
e   30       Nepal
f   35      Canada

In [ ]:
print(dfe.iloc[3])
print(dfe.loc['b'])

In [ ]:
# print(dfe[dfe['Age']>30])
print(dfe[(dfe['Marks']>50) & (dfe['Age']>30)])
# print(dfe[(dfe['Marks'] > 50) & (dfe['Age'] > 30)])

    Name  Age Country  Marks
f  Bahar   35  Canada     80

In [ ]:
print(dfe[dfe['Country']=="Japan"])
filtered_df = dfe[dfe['Country'].isin(['Japan', 'China'])]
print(filtered_df)

     Name  Age Country  Marks
d  Junaed   29   Japan     33
     Name  Age Country  Marks
c    Khan   28   China     50
d  Junaed   29   Japan     33

In [ ]:
print(dfe[dfe['Country'].isin(['Japan',"China"])])

     Name  Age Country  Marks
c    Khan   28   China     50
d  Junaed   29   Japan     33

In [ ]:
print(dfe.describe())

             Age     Marks
count   6.000000   6.00000
mean   28.833333  63.00000
std     3.544949  26.01538
min    25.000000  33.00000
25%    26.500000  41.75000
50%    28.500000  64.00000
75%    29.750000  79.50000
max    35.000000  98.00000

In [ ]:
print(dfe['Age'].mean())

28.833333333333332

In [ ]:
print(dfe.sort_values(by='Age',ascending=False))

     Name  Age     Country  Marks
f   Bahar   35      Canada     80
e  Siddik   30       Nepal     78
d  Junaed   29       Japan     33
c    Khan   28       China     50
b   Rasel   26    Pakistan     39
a    Abid   25  Bangladesh     98

## **Pandas**

In [ ]:
import pandas as pd

path = "/content/drive/MyDrive/Colab Notebooks/Students.csv"
df = pd.read_csv(path)

df.head()

     Name  Age     Country  Marks
0   Akash   25         USA     80
1  Batash   30      France     60
2   pahar   35     Germany     85
3  Shobuj   20  Bangladesh     64
4   Sagor   45    Pakistan     49

In [ ]:
print(df.iloc[1])

Name       Batash
Age            30
Country    France
Marks          60
Name: 1, dtype: object

In [ ]:
print(df[(df['Age']>30) & (df['Age']<45)])

     Name  Age  Country  Marks
2   pahar   35  Germany     85
5    Nodi   40       UK     82
7    Duba   39  Finland     93
10   Khan   37    Saudi     35

In [ ]:
print(df[["Age","Country"]])

    Age     Country
0    25         USA
1    30      France
2    35     Germany
3    20  Bangladesh
4    45    Pakistan
5    40          UK
6    24   Australia
7    39     Finland
8    60      Canada
9    70  Newzealand
10   37       Saudi

In [ ]:
print(dfe[dfe['Country'].isin(['Japan',"China"])])

     Name  Age Country  Marks
c    Khan   28   China     50
d  Junaed   29   Japan     33

In [ ]:
df[df['Country'].isin(['USA', 'Canada'])]['Name']

0    Akash
8     Abid
Name: Name, dtype: object

In [ ]:
print(df.loc[df['Country'].isin(['USA', 'Canada']), 'Name'])

0    Akash
8     Abid
Name: Name, dtype: object