Feature Engineering means: Make smarter the data

Creating new useful features (columns) from existing data to help the model learn better.
Complete Machine Learning Workflow

This is how a real project looks.
Collect Data
      │
      ▼
Understand Data
      │
      ▼
EDA
      │
      ▼
Data Cleaning
      │
      ▼
Feature Engineering
      │
      ▼
Feature Selection
      │
      ▼
Split Train/Test
      │
      ▼
Scaling & Encoding
      │
      ▼
Build Model
      │
      ▼
Evaluate
      │
      ▼
Improve
      │
      ▼
Deploy

EDA: Understand data, Question like: How many missing values?

Any outliers?

Distribution?

Relationships?

Patterns?
EDA is like being a detective

Data Preprocessing: Fix data, Qustion like: Fill missing values

Encode text

Scale numbers

Remove duplicates

Prepare for ML

Data Preprocessing include: It includes much more:

Encoding
Scaling
Feature engineering
Pipelines
Transformations

## Lesson 2 — Data Cleaning (Industry-Level)

In [1]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Employee_ID":[101,102,103,104,104,106,107,108],

    "Name":[
        "Abid",
        "Sara",
        "john",
        " Mina ",
        " Mina ",
        np.nan,
        "Alex",
        "EMMA"
    ],

    "Age":[
        22,
        "23",
        "Twenty Four",
        25,
        25,
        -3,
        29,
        np.nan
    ],

    "Department":[
        "IT",
        "HR",
        "IT",
        "Finance",
        "Finance",
        "IT",
        "hr",
        "Finance"
    ],

    "Salary":[
        30000,
        35000,
        np.nan,
        45000,
        45000,
        -5000,
        52000,
        60000
    ],

    "Join_Date":[
        "2023-01-15",
        "2022/05/10",
        "15-08-2021",
        "2023-07-20",
        "2023-07-20",
        "Unknown",
        "2024-01-05",
        "2024-02-30"
    ]
})

print(df)

   Employee_ID    Name          Age Department   Salary   Join_Date
0          101    Abid           22         IT  30000.0  2023-01-15
1          102    Sara           23         HR  35000.0  2022/05/10
2          103    john  Twenty Four         IT      NaN  15-08-2021
3          104   Mina            25    Finance  45000.0  2023-07-20
4          104   Mina            25    Finance  45000.0  2023-07-20
5          106     NaN           -3         IT  -5000.0     Unknown
6          107    Alex           29         hr  52000.0  2024-01-05
7          108    EMMA          NaN    Finance  60000.0  2024-02-30

In [2]:
df.head()

   Employee_ID    Name          Age Department   Salary   Join_Date
0          101    Abid           22         IT  30000.0  2023-01-15
1          102    Sara           23         HR  35000.0  2022/05/10
2          103    john  Twenty Four         IT      NaN  15-08-2021
3          104   Mina            25    Finance  45000.0  2023-07-20
4          104   Mina            25    Finance  45000.0  2023-07-20

In [3]:
df.tail()

   Employee_ID    Name  Age Department   Salary   Join_Date
3          104   Mina    25    Finance  45000.0  2023-07-20
4          104   Mina    25    Finance  45000.0  2023-07-20
5          106     NaN   -3         IT  -5000.0     Unknown
6          107    Alex   29         hr  52000.0  2024-01-05
7          108    EMMA  NaN    Finance  60000.0  2024-02-30

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Employee_ID  8 non-null      int64
 1   Name         7 non-null      str
 2   Age          7 non-null      object
 3   Department   8 non-null      str
 4   Salary       7 non-null      float64
 5   Join_Date    8 non-null      str
dtypes: float64(1), int64(1), object(1), str(3)
memory usage: 516.0+ bytes

In [5]:
df.describe(include="all")

        Employee_ID    Name   Age Department        Salary   Join_Date
count      8.000000       7   7.0          8      7.000000           8
unique          NaN       6   6.0          4           NaN           7
top             NaN   Mina   25.0         IT           NaN  2023-07-20
freq            NaN       2   2.0          3           NaN           2
mean     104.375000     NaN   NaN        NaN  37428.571429         NaN
std        2.445842     NaN   NaN        NaN  21204.222401         NaN
min      101.000000     NaN   NaN        NaN  -5000.000000         NaN
25%      102.750000     NaN   NaN        NaN  32500.000000         NaN
50%      104.000000     NaN   NaN        NaN  45000.000000         NaN
75%      106.250000     NaN   NaN        NaN  48500.000000         NaN
max      108.000000     NaN   NaN        NaN  60000.000000         NaN

In [6]:
df.describe()

       Employee_ID        Salary
count     8.000000      7.000000
mean    104.375000  37428.571429
std       2.445842  21204.222401
min     101.000000  -5000.000000
25%     102.750000  32500.000000
50%     104.000000  45000.000000
75%     106.250000  48500.000000
max     108.000000  60000.000000

In [7]:
df.isnull().sum()

Employee_ID    0
Name           1
Age            1
Department     0
Salary         1
Join_Date      0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(1)

In [ ]:
df[df.duplicated()] # find duplicates rows

   Employee_ID    Name Age Department   Salary   Join_Date
4          104   Mina   25    Finance  45000.0  2023-07-20

In [10]:
df = df.drop_duplicates() # remove duplicates and return new dataframe

In [11]:
df.dtypes

Employee_ID      int64
Name               str
Age             object
Department         str
Salary         float64
Join_Date          str
dtype: object

In [13]:
df["Age"] = pd.to_numeric(
    df["Age"],
    errors="coerce"
) # errors="coerce" will convert non-numeric values to NaN

In [14]:
df["Department"] = (
    df["Department"]
      .str.strip()
      .str.title()
)

In [15]:
df["Name"] = (
    df["Name"]
      .str.strip()
      .str.title()
)

In [16]:
df[df["Age"] < 0]

   Employee_ID Name  Age Department  Salary Join_Date
5          106  NaN -3.0         It -5000.0   Unknown

In [17]:
df[df["Salary"] < 0]

   Employee_ID Name  Age Department  Salary Join_Date
5          106  NaN -3.0         It -5000.0   Unknown

In [18]:
df.loc[df["Age"] < 0, "Age"] = np.nan

In [ ]:
df.loc[df["Age"] < 0, "Age"] = np.nan # .loc[row_condition, column_name] to update only the problematic cells.

In [ ]:
df["Join_Date"] = pd.to_datetime(
    df["Join_Date"],
    errors="coerce"
) # nvalid dates become NaT (Not a Time), which is the datetime equivalent of NaN.

In [21]:
df

   Employee_ID  Name   Age Department   Salary  Join_Date
0          101  Abid  22.0         It  30000.0 2023-01-15
1          102  Sara  23.0         Hr  35000.0        NaT
2          103  John   NaN         It      NaN        NaT
3          104  Mina  25.0    Finance  45000.0 2023-07-20
5          106   NaN   NaN         It  -5000.0        NaT
6          107  Alex  29.0         Hr  52000.0 2024-01-05
7          108  Emma   NaN    Finance  60000.0        NaT

In [22]:
print(df.info())
print(df.head())

<class 'pandas.DataFrame'>
Index: 7 entries, 0 to 7
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Employee_ID  7 non-null      int64
 1   Name         6 non-null      str
 2   Age          4 non-null      float64
 3   Department   7 non-null      str
 4   Salary       6 non-null      float64
 5   Join_Date    3 non-null      datetime64[us]
dtypes: datetime64[us](1), float64(2), int64(1), str(2)
memory usage: 392.0 bytes
None
   Employee_ID  Name   Age Department   Salary  Join_Date
0          101  Abid  22.0         It  30000.0 2023-01-15
1          102  Sara  23.0         Hr  35000.0        NaT
2          103  John   NaN         It      NaN        NaT
3          104  Mina  25.0    Finance  45000.0 2023-07-20
5          106   NaN   NaN         It  -5000.0        NaT

In [23]:
df["Name"] = df["Name"].str.title()

In [24]:
df.isna().sum()

Employee_ID    0
Name           1
Age            3
Department     0
Salary         1
Join_Date      4
dtype: int64

In [27]:
"""
lesson.py

Mini Project:
Employee Data Inspection & Cleaning

Tasks:
1. Load the dataset
2. Inspect the dataset
3. Remove duplicate rows
4. Fix incorrect data types
5. Standardize text values
6. Handle impossible values
7. Convert date columns
8. Print before-and-after summaries

Author: Your Name
"""

# ==========================================================
# Import Libraries
# ==========================================================

import pandas as pd
import numpy as np

# ==========================================================
# Load Dataset
# ==========================================================

df = pd.DataFrame({
    "Employee_ID":[101,102,103,104,104,106,107,108],

    "Name":[
        "Abid",
        "Sara",
        "john",
        " Mina ",
        " Mina ",
        np.nan,
        "Alex",
        "EMMA"
    ],

    "Age":[
        22,
        "23",
        "Twenty Four",
        25,
        25,
        -3,
        29,
        np.nan
    ],

    "Department":[
        "IT",
        "HR",
        "IT",
        "Finance",
        "Finance",
        "IT",
        "hr",
        "Finance"
    ],

    "Salary":[
        30000,
        35000,
        np.nan,
        45000,
        45000,
        -5000,
        52000,
        60000
    ],

    "Join_Date":[
        "2023-01-15",
        "2022/05/10",
        "15-08-2021",
        "2023-07-20",
        "2023-07-20",
        "Unknown",
        "2024-01-05",
        "2024-02-30"
    ]
})

print(df)

# ==========================================================
# BEFORE CLEANING SUMMARY
# ==========================================================

print("=" * 50)
print("BEFORE CLEANING")
print("=" * 50)

print("\nFirst Five Rows")
print(df.head())

print("\nDataset Information")
print(df.info())

print("\nSummary Statistics")
print(df.describe(include="all"))

print("\nMissing Values")
print(df.isnull().sum())

print("\nDuplicate Rows:", df.duplicated().sum())

# ------------------------------------------
# Remove Duplicates
# ------------------------------------------

duplicates_before = df.duplicated().sum()

df = df.drop_duplicates()

duplicates_after = df.duplicated().sum()

# ------------------------------------------
# Fix Data Types
# ------------------------------------------

df["Age"] = pd.to_numeric(
    df["Age"],
    errors="coerce"
)

df["Salary"] = pd.to_numeric(
    df["Salary"],
    errors="coerce"
)

# ------------------------------------------
# Standardize Text
# ------------------------------------------

df["Name"] = (
    df["Name"]
    .str.strip()
    .str.title()
)

df["Department"] = (
    df["Department"]
    .str.strip()
    .str.upper()
)

df["Name"] = df["Name"].fillna("Unknown")

# ------------------------------------------
# Handle Impossible Values
# ------------------------------------------

df.loc[df["Age"] < 0, "Age"] = np.nan
df.loc[df["Salary"] < 0, "Salary"] = np.nan

df["Age"] = df["Age"].fillna(df["Age"].median())
df["Salary"] = df["Salary"].fillna(df["Salary"].median())

# ------------------------------------------
# Convert Dates
# ------------------------------------------

df["Join_Date"] = pd.to_datetime(
    df["Join_Date"],
    errors="coerce",
    dayfirst=True
)

   Employee_ID    Name          Age Department   Salary   Join_Date
0          101    Abid           22         IT  30000.0  2023-01-15
1          102    Sara           23         HR  35000.0  2022/05/10
2          103    john  Twenty Four         IT      NaN  15-08-2021
3          104   Mina            25    Finance  45000.0  2023-07-20
4          104   Mina            25    Finance  45000.0  2023-07-20
5          106     NaN           -3         IT  -5000.0     Unknown
6          107    Alex           29         hr  52000.0  2024-01-05
7          108    EMMA          NaN    Finance  60000.0  2024-02-30
==================================================
BEFORE CLEANING
==================================================

First Five Rows
   Employee_ID    Name          Age Department   Salary   Join_Date
0          101    Abid           22         IT  30000.0  2023-01-15
1          102    Sara           23         HR  35000.0  2022/05/10
2          103    john  Twenty Four         IT      NaN  15-08-2021
3          104   Mina            25    Finance  45000.0  2023-07-20
4          104   Mina            25    Finance  45000.0  2023-07-20

Dataset Information
<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Employee_ID  8 non-null      int64
 1   Name         7 non-null      str
 2   Age          7 non-null      object
 3   Department   8 non-null      str
 4   Salary       7 non-null      float64
 5   Join_Date    8 non-null      str
dtypes: float64(1), int64(1), object(1), str(3)
memory usage: 516.0+ bytes
None

Summary Statistics
        Employee_ID    Name   Age Department        Salary   Join_Date
count      8.000000       7   7.0          8      7.000000           8
unique          NaN       6   6.0          4           NaN           7
top             NaN   Mina   25.0         IT           NaN  2023-07-20
freq            NaN       2   2.0          3           NaN           2
mean     104.375000     NaN   NaN        NaN  37428.571429         NaN
std        2.445842     NaN   NaN        NaN  21204.222401         NaN
min      101.000000     NaN   NaN        NaN  -5000.000000         NaN
25%      102.750000     NaN   NaN        NaN  32500.000000         NaN
50%      104.000000     NaN   NaN        NaN  45000.000000         NaN
75%      106.250000     NaN   NaN        NaN  48500.000000         NaN
max      108.000000     NaN   NaN        NaN  60000.000000         NaN

Missing Values
Employee_ID    0
Name           1
Age            1
Department     0
Salary         1
Join_Date      0
dtype: int64

Duplicate Rows: 1

C:\Users\HP\AppData\Local\Temp\ipykernel_2188\2285732506.py:170: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df["Join_Date"] = pd.to_datetime(

In [29]:
dfe = pd.DataFrame({
    "Employee_ID":[101,102,103,104,104,106,107,108],

    "Name":[
        "Abid",
        "Sara",
        "john",
        " Mina ",
        " Mina ",
        np.nan,
        "Alex",
        "EMMA"
    ],

    "Age":[
        22,
        "23",
        "Twenty Four",
        25,
        25,
        -3,
        29,
        np.nan
    ],

    "Department":[
        "IT",
        "HR",
        "IT",
        "Finance",
        "Finance",
        "IT",
        "hr",
        "Finance"
    ],

    "Salary":[
        30000,
        35000,
        np.nan,
        45000,
        45000,
        -5000,
        52000,
        60000
    ],

    "Join_Date":[
        "2023-01-15",
        "2022/05/10",
        "15-08-2021",
        "2023-07-20",
        "2023-07-20",
        "Unknown",
        "2024-01-05",
        "2024-02-30"
    ]
})

print(dfe)

   Employee_ID    Name          Age Department   Salary   Join_Date
0          101    Abid           22         IT  30000.0  2023-01-15
1          102    Sara           23         HR  35000.0  2022/05/10
2          103    john  Twenty Four         IT      NaN  15-08-2021
3          104   Mina            25    Finance  45000.0  2023-07-20
4          104   Mina            25    Finance  45000.0  2023-07-20
5          106     NaN           -3         IT  -5000.0     Unknown
6          107    Alex           29         hr  52000.0  2024-01-05
7          108    EMMA          NaN    Finance  60000.0  2024-02-30

In [34]:
dfe.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Employee_ID  8 non-null      int64
 1   Name         7 non-null      str
 2   Age          7 non-null      object
 3   Department   8 non-null      str
 4   Salary       7 non-null      float64
 5   Join_Date    8 non-null      str
dtypes: float64(1), int64(1), object(1), str(3)
memory usage: 516.0+ bytes

In [31]:
print(dfe["Age"].unique())

[22 '23' 'Twenty Four' 25 -3 29 nan]

In [35]:
dfe["Age"] = dfe["Age"].replace({
    "Twenty Four": 24
})

In [37]:
# convert the "Age" column to numeric type, coercing errors to NaN
dfe["Age"] = dfe["Age"].replace("Twenty Four", 24)

dfe["Age"] = pd.to_numeric(
    dfe["Age"],
    errors="coerce"
)

In [38]:
dfe

   Employee_ID    Name   Age Department   Salary   Join_Date
0          101    Abid  22.0         IT  30000.0  2023-01-15
1          102    Sara  23.0         HR  35000.0  2022/05/10
2          103    john  24.0         IT      NaN  15-08-2021
3          104   Mina   25.0    Finance  45000.0  2023-07-20
4          104   Mina   25.0    Finance  45000.0  2023-07-20
5          106     NaN  -3.0         IT  -5000.0     Unknown
6          107    Alex  29.0         hr  52000.0  2024-01-05
7          108    EMMA   NaN    Finance  60000.0  2024-02-30